# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HappyShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HappyShop
    pod 'RealmSwift'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'Alamofire',  '~> 4.5'


  target 'HappyShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappyShopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
